apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  securityContext: # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
    runAsNonRoot: false # to specify a user, we'll have to add a user in the dockerfile for the image below
  automountServiceAccountToken: false
  containers:
  - name: mycontainer
    image: public.ecr.aws/docker/library/busybox:latest
    imagePullPolicy: Always
    command:
      - 'sh'
      - '-c'
      - 'echo "The credential is $SECRET_USERNAME:$SECRET_PASSWORD"'
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: username
            optional: false # same as default; "mysecret" must exist # and include a key named "username"      
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-user-pass
            key: password
            optional: false # same as default; "mysecret" must exist and include a key named "password"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m" 
    securityContext:
      allowPrivilegeEscalation: true     
      readOnlyRootFilesystem: true                                   
  restartPolicy: Never