# Restore a Persistent Volume Claim from the Volume snapshot
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appserver-recovery-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: disaster-recovery
  resources:
    requests:
      storage: 2Gi
  dataSource:
    name: ebs-volume-snapshot  # <----- name must match the snapshot name 
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: appserver-recovery
spec:
  containers:
  - name: appserver
    image: busybox:1.36
    command: ["/bin/sh","-c","tail -f /data/out.txt"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"      
    securityContext:
      allowPrivilegeEscalation: true  # modify this depending on your use case    
      readOnlyRootFilesystem: false # modify this depending on your use case     
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: appserver-recovery-claim # <---- must match the restored Persistent Volume Claim