# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# A sample workflow which checks out your code and scans your desired k8s config files for misconfigurations using the Datree CLI.
# The results are then uploaded to GitHub Security Code Scanning.
#
# For more information and configurations options, see https://github.com/datreeio/action-datree/

name: Datree

on:
  push:
    branches: [ "main" ]

  pull_request_target:
    types: [assigned, opened, synchronize, reopened]
    branches: [ "main" ]

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
  
permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results    

jobs:
  k8sPolicyCheck:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test *.yml files with Datree 
      # pass on failure so that code report upload can succeed 
        # continue-on-error: true   
        uses: datreeio/action-datree@de67ae7a5133d719dc794e1b75682cd4c5f94d8a
        with:
          # Add the path to the configuration file/s that you would like to test.
          # See https://github.com/datreeio/action-datree#usage for all available options.
          path: 'examples/kubernetes/*/*.yml'
          # Setting a SARIF output will generate a file named "datree.sarif" containing your test results
          cliArguments: "-o sarif --only-k8s-files"

      - name: Test *.yaml files with Datree 
      # pass on failure so that code report upload can succeed 
        # continue-on-error: true   
        uses: datreeio/action-datree@de67ae7a5133d719dc794e1b75682cd4c5f94d8a
        if: success() || failure() 
        with:
          # Add the path to the configuration file/s that you would like to test.
          # See https://github.com/datreeio/action-datree#usage for all available options.
          path: 'examples/kubernetes/*/*.yaml'
          # Setting a SARIF output will generate a file named "datree.sarif" containing your test results
          cliArguments: "-o sarif --only-k8s-files"

      - name: Run Datree Policy Check Helm Charts
        uses: datreeio/action-datree@main
        if: success() || failure() 
        with:
          path: 'examples/helm/./'
          cliArguments: ''
          isHelmChart: true
          helmArguments: '--values values.yaml'     

      - name: Upload result to GitHub Code Scanning to be displayed as security alerts 
        uses: github/codeql-action/upload-sarif@v2

        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()        
        with:
          sarif_file: datree.sarif
          wait-for-processing: true

